#22 Add bootstrap alerts
OSLL/web_speech_trainer pull request #174
Opened 2021-04-07 21:28 UTC by Anya18

2021-04-07 21:38 UTC, Anya18 commented
Есть ошибка при обращении к стилям в static/css/ из training.html

2021-04-13 16:53 UTC, Plyushchenko requested changes

2021-04-13 16:53 UTC, Plyushchenko commented on app/static/js/upload.js
> +function onChange(){
IDE (например, PyCharm или WebStorm) справляется с форматированием.
Также при желании можно установить форматтер какой-нибудь.

2021-04-13 16:53 UTC, Plyushchenko commented on app/templates/error.html
> +            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
Пожалуйста, добавьте этот файл в `app/static/js/libraries/`.

2021-04-13 16:53 UTC, Plyushchenko commented on app/static/js/upload.js
> +        if (file.size > 10000000){
Я не уверен, что клиенту стоит знать о конфиге, но давайте хотя бы с этим самым конфигом согласуемся, там сейчас ограничение на 16 мегабайт, т.е. 16 * 1024 * 1024 bytes в качестве константы где-нибудь, видимо, стоит завести.

2021-04-13 16:53 UTC, Plyushchenko commented on app/static/js/upload.js
> +        str = "Select file!"
В каком случае появляется эта надпись?

2021-04-13 16:53 UTC, Plyushchenko commented on app/static/js/upload.js
> +                str = "Presentation file should not exceed 10MB"
Если загрузить слишком большой файл, то увидим алерт на странице загрузки, а потом на отдельной странице. Так и задумано?

2021-04-27 18:25 UTC, Anya18 commented on app/static/js/upload.js
> +                str = "Presentation file should not exceed 10MB"
Данная проблема будет исправлена после выполнения задачи #135 когда кнопка "Начать тренировку" будет становиться активной только после загрузки файла и прохождении проверок, сделанных в данной задаче на клиентской стороне

2021-04-29 13:06 UTC, merged