#110 Add training timer
OSLL/web_speech_trainer pull request #189
Opened 2021-04-13 14:13 UTC by Anya18

Add timer without red zone

2021-04-20 13:30 UTC, Plyushchenko requested changes

2021-04-20 13:30 UTC, Plyushchenko commented on app/static/js/recording.js
> +                let strTimer = `Training time: ${Math.trunc(hour)}:${Math.trunc(minuts)}:${seconds}`;
Получаются строки вида: `Training time: 0:3:5`. Думаю, более привычно видеть два разряда.

2021-04-20 13:30 UTC, Plyushchenko commented on app/static/js/recording.js
> +                if (maxTime && time >= maxTime) {
Точно хотелось, чтобы текст просто покраснел, без каких-либо других эффектов?

2021-04-20 13:30 UTC, Plyushchenko commented on app/static/js/recording.js
> +                })
Думаю, лучше везде ставить `;`, т.е. писать одинаково.

2021-04-20 13:44 UTC, Anya18 commented on app/static/js/recording.js
> +                if (maxTime && time >= maxTime) {
Насколько я помню, в обсуждении этой задачи не упоминались другие эффекты. Однако их можно добавить, если появились какие-то предложения.

2021-04-20 19:12 UTC, Plyushchenko commented on app/static/js/recording.js
> +                let strTimer = `Training time: ${Math.trunc(hour)}:${minuts}:${seconds}`;
Решили надписи делать на русском

2021-04-25 21:40 UTC, Plyushchenko approved these changes

2021-04-25 21:41 UTC, merged