[WST-15] Запись аудио на странице тренировки
OSLL/web_speech_trainer pull request #19
Opened 2020-09-21 00:02 UTC by Plyushchenko

2020-09-23 08:38 UTC, zmm requested changes

2020-09-23 08:38 UTC, zmm commented on requirements.txt
> +vext.gi
не хватает playsound

2020-09-23 08:38 UTC, zmm commented on app/web_speech_trainer.py
> +@app.route('/presentation_record', methods=['POST'])
добавьте также получение записи по GET

2020-09-23 08:38 UTC, zmm commented on app/web_speech_trainer.py
>          if request.content_length > PRESENTATION_FILE_MAX_SIZE_IN_MEGABYTES * BYTES_IN_MEGABYTE:
вынесите PRESENTATION_FILE_MAX_SIZE_IN_MEGABYTES в конфиг

2020-09-23 08:38 UTC, zmm commented on app/static/js/recording.js
> +
Оберните инициализацию переменных и вызовы в глобальном контексте в $(document).ready(function(){

})

2020-09-23 08:38 UTC, zmm commented on app/static/js/recording.js
> +recordButton.addEventListener('click', startRecording);
Используйте здесь и далее синтаксис jquery - он более емкий:
```
$('#record').click(startRecording)
```

2020-09-23 08:38 UTC, zmm commented on app/static/js/training.js
> -var url = 'static/test.pdf';
Замечания аналогичны app/static/js/recording.js

2020-09-28 17:25 UTC, Plyushchenko commented on app/web_speech_trainer.py
> +@app.route('/presentation_record', methods=['POST'])
Добавил

2020-09-28 17:26 UTC, Plyushchenko commented on requirements.txt
> +vext.gi
Убрал, playsound не используется

2020-10-07 11:40 UTC, zmm requested changes
Загружаю файл (приложил) , 
[manual.pdf](https://github.com/OSLL/web_speech_trainer/files/5340362/manual.pdf)

получаю вот такое на странице /upload 

![image](https://user-images.githubusercontent.com/717575/95326282-ff8faa80-08aa-11eb-8926-081759e10e2d.png)

2020-10-07 12:22 UTC, zmm approved these changes

2020-10-07 12:22 UTC, merged