#162 Set time format GMT+3
OSLL/web_speech_trainer pull request #211
Opened 2021-05-05 11:52 UTC by Anya18

2021-05-07 10:56 UTC, Plyushchenko requested changes

2021-05-07 10:56 UTC, Plyushchenko commented on app/static/js/show_all_trainings.js
> +    if (isNaN(timestamp_start) == false) {
if (... == false) это if (!...)

2021-05-07 10:56 UTC, Plyushchenko commented on app/static/js/show_all_trainings.js
> +    timestamp_finish = Date.parse(trainingJson["processing_finish_timestamp"]);
строки 26--32 и 36--42 делают одно и то же, можно вынести в функцию

2021-05-07 10:56 UTC, Plyushchenko commented on app/static/js/show_all_trainings.js
> +        trainingProcessingStartTimestampElement.textContent = "";
Так если NaN, то ячейка и так пустая будет, разве нет?

2021-05-12 16:03 UTC, Anya18 commented on app/static/js/show_all_trainings.js
> +        trainingProcessingStartTimestampElement.textContent = "";
Нет, в ячейке будет надпись в стиле "Invalid date"

2021-06-02 11:51 UTC, Plyushchenko approved these changes

2021-06-02 11:51 UTC, merged