#101 Add columns to table
OSLL/web_speech_trainer pull request #228
Opened 2021-06-18 16:19 UTC by Anya18

2021-06-30 09:37 UTC, Anya18 commented
Скринкаст варианта с загрузкой презентации: https://youtu.be/RD2vRKUoO9I
Скринкаст варианта с открытием презентации в браузере: https://youtu.be/TEEQytYOBcg

2021-06-30 16:28 UTC, HadronCollider requested changes
- страницу с презентацией стоит открывать в новой вкладке (атрибут `target='_blank'` у `<a>`)
- кажется, не хватает адаптивности для таблицы, иначе с новыми столбцами картина становится следующей (@Plyushchenko, или, возможно, это норм? полей действительно много):
![image](https://user-images.githubusercontent.com/21632402/123997137-bb17e200-d9d8-11eb-95ad-7e95d6980a77.png)

2021-07-05 14:42 UTC, zmm commented
Предлагаю компромисс - давайте отображать последние 5 знаков из id тренировок и презентаций (вместо полного id) + сделать отдельную задачу на адаптивность

2021-07-06 18:56 UTC, HadronCollider approved these changes

2021-07-06 18:56 UTC, merged