342_ask_close_window
OSLL/web_speech_trainer pull request #383
Opened 2023-07-04 12:33 UTC by severus2293

Попытка выйти до записи:
![342_до_записи](https://github.com/OSLL/web_speech_trainer/assets/71723580/372353f0-bee7-4b9d-a86e-7ac50358acbd)

Попытка выйти во время записи:
![342_во_время_записи](https://github.com/OSLL/web_speech_trainer/assets/71723580/5e6df4ed-065f-4e77-8085-bef031332bcf)

Попытка выйти во время и после обработки:
![342_после_обработки](https://github.com/OSLL/web_speech_trainer/assets/71723580/cddc8120-e384-4813-9aa3-b5c49fa20731)

2023-07-04 12:37 UTC, severus2293 commented
![Снимок экрана (48)](https://github.com/OSLL/web_speech_trainer/assets/71723580/7df05673-2ef5-421f-80b0-4db523db147e)
![Снимок экрана (49)](https://github.com/OSLL/web_speech_trainer/assets/71723580/1ef61c50-9c05-442f-b4e3-868f203b35d8)
Примечание: при заходе на страницу до начала записи onbeforeunload отработает если пользователь хотя бы нажмёт на страницу. Другого функционала по определению выхода пользователя со страницы кроме onbeforeunload в js нет.

2023-07-10 09:47 UTC, HadronCollider approved these changes

2023-07-10 09:49 UTC, HadronCollider requested changes
- Решите конфликты
- баг: рри завершении тренировки (после того, как спрашивают "закончить тренировку?") при выходе со страницы срабатывает проверка на закрытие страницы (как во время тренировки) - хотя вроде бы прописано
```js
 window.onbeforeunload = function () {
        return false;
 }
```

2024-03-06 14:36 UTC, HadronCollider approved these changes

2024-03-06 14:36 UTC, merged