deploy whisper
OSLL/web_speech_trainer pull request #388
Opened 2023-11-09 19:54 UTC by arhihihipov

2024-02-26 06:57 UTC, zmm commented on app/audio_recognizer.py
> +            'language': 'ru',
сделайте язык параметром (чтобы на будущее можно было его менять )

2024-02-26 06:58 UTC, zmm commented on requirements.txt
> +librosa
Добавьте версии для библиотек requests и librosa

2024-03-06 19:13 UTC, HadronCollider commented on docker-compose.yml
> +  whisper:
Дополнительных наблюдений
- whisper достаточно прожорлив на ЦПУ - добавьте ограничение на ЦП по аналогии с примером ниже
```
services:
  web:
    build: .
    restart: always
    ports:
      - "8888:8888"
    cpuset: ${CONTAINER_CPU:-0-1}  # CONTAINER_CPU в .env - если не будет, берется по умолчанию 0-1
``` 
- каждый раз при запуске контейнера скачивается модель - смонтируйте каталог, куда они скачиваются в контейнере, в отдельный volume - так не нужно будет постоянно скачивать одну и ту же модель (система проверит её наличие, обновит при необходимости)

2024-03-07 12:46 UTC, HadronCollider reviewed
Аналогичное замечание про ОЗУ - https://github.com/OSLL/web_speech_trainer/pull/388/files#r1515013316
- локально у меня могло "съесть" неконтролируемо до 5+ ГБ

Плюс изучите риски подобного поведения:
![image](https://github.com/OSLL/web_speech_trainer/assets/21632402/2e2a701a-49c6-4706-99f4-cfa993305fad)

2024-03-07 19:26 UTC, HadronCollider commented
Добавил/освежил Github CI для более простой проверки интеграции

К комментарию - https://github.com/OSLL/web_speech_trainer/pull/388#discussion_r1514697816, сейчас падают только ваши тесты
```
collected 50 items

test_app.py ..                                                           [  4%]
test_audio_conversion.py ..                                              [  8%]
test_feedback_evaluator.py ......                                        [ 20%]
test_presentations.py .                                                  [ 22%]
test_whisper.py E                                                        [ 24%]
api/test_audio.py ...                                                    [ 30%]
api/test_files.py ...............                                        [ 60%]
api/test_task_attempts.py ...                                            [ 66%]
criteria/test_criteria.py ...                                            [ 72%]
criteria/test_strict_speech_duration_criterion.py .............          [ 98%]
selenium/test_training.py .                                              [100%]
```

2024-03-10 15:31 UTC, arhihihipov commented on tests/test_whisper.py
Соглашусь, такой код для тестирования не подойдёт. Хотелось бы узнать, стоит ли вообще писать тест для Whisper, и если да, то что именно нужно протестировать

2024-03-10 15:43 UTC, arhihihipov commented on app/audio_recognizer.py
> +        data = response.json()
Подойдёт ли для этих целей конструкция try except?
```
    try:
    ***

    except requests.exceptions.RequestException as e:
        print(f"An error occurred: {e}")
        return None
```

2024-03-11 08:25 UTC, arhihihipov commented on app/audio_recognizer.py
> +        files = {'audio_file': (file_name, open(file_name, 'rb'), 'audio/mpeg')}
Не совсем понимаю, как это можно проверить в коде, и нужно ли? 
Я немного переписал эту часть кода — добавил закрытие файла после прочтения, теперь посылаю не дескриптор, а буфер, в который файл был считан

2024-03-12 07:35 UTC, HadronCollider commented on app/audio_recognizer.py
> +        data = response.json()
Да, только пишите в логи через logger

2024-03-12 07:38 UTC, HadronCollider commented on app/audio_recognizer.py
> +        files = {'audio_file': (file_name, open(file_name, 'rb'), 'audio/mpeg')}
Тут скорее вопрос (на исследование/проверку) - какого максимального размера аудио можно отправить в asr? И можно ли защититься от ошибок со слишком большими файлами (разбивать их на более мелкие / др) - в vosk данные отправлялись кусками по сокету, поэтому теоретически происходила обработка аудио любого размера

2024-03-12 07:41 UTC, HadronCollider commented on tests/test_whisper.py
Добавьте тестирование своего класса WhisperAudioRecognizer (пусть даже он частично будет общаться с whisper-контейнером, и это будет уже не совсем unit-тестирование)

2024-03-12 07:49 UTC, HadronCollider commented on .env
env не пушьте - добавьте в гитигнор, его будем локально ставить (значения по умолчанию для переменных в yml вы указали, поэтому всё будет работать и без него)

2024-03-12 20:11 UTC, arhihihipov commented on tests/test_whisper.py
![image](https://github.com/OSLL/web_speech_trainer/assets/71722818/2a015dfc-eac5-4d8e-ae64-adbcea0b9c24)
Возникли трудности с написанием тестов, дело в том, что на данный момент tiny модель "Добрый день, все хорошо. Я сижу дома" распознаёт так, как показано на фото. Первая строка результат распознавания после применений denoiser, перегона в wav, а на второй строке результат распознавания необработанной записи

2024-03-20 17:43 UTC, HadronCollider commented on tests/test_whisper.py
Давайте пока оставим тесты в том виде в котором есть (с печатью распознанных слов)

2024-03-20 17:48 UTC, HadronCollider requested changes
Оставил последние комментарии - остальное ок

2024-03-20 17:48 UTC, HadronCollider commented on app/audio_processor.py
> +                logger.info(f'audio processing time: {processing_time} s')
Добавьте в сообщение длительность аудио (вы её получаете выше) - так будут более полезные логи (длина записи + время её обработки)

2024-03-20 17:48 UTC, HadronCollider commented on docker-compose.yml
> +      - ./whisper_asr_model_cache:/root/.cache/whisper
Чтобы не засорять хост/папку репо (и не трогать docker/gitignore) - сделайте docker volume ( https://docs.docker.com/compose/compose-file/07-volumes/ )

2024-03-20 17:48 UTC, HadronCollider commented on docker-compose.yml
> +    mem_limit: 5g
Вынесите параметр по аналогии в env

2024-03-20 17:56 UTC, HadronCollider commented on app/audio_recognizer.py
> +        files = {'audio_file': (file_name, open(file_name, 'rb'), 'audio/mpeg')}
Вынесите свои исследования в https://github.com/OSLL/web_speech_trainer/wiki

2024-03-20 18:00 UTC, HadronCollider commented on tests/test_whisper.py
А по поводу wav и denoiser - посмотрите, насколько они нужны при работе с whisper (создал задачу - https://github.com/OSLL/web_speech_trainer/issues/401 ) - wav нужен был для vosk, возможно, сейчас от него можно избавиться?

2024-03-21 07:52 UTC, HadronCollider commented
Возможно, максимально запоздалый вопрос, но тем не менее - какие есть причины, чтобы держать его в отдельном контейнере (кроме того, что так было с vosk)?

Whisper можно использовать из python - это решает часть проблем и опасений, связанных с http запросами к ASR 
![Screenshot_2024-03-21-10-45-54-356_com.github.android.jpg](https://github.com/OSLL/web_speech_trainer/assets/21632402/f90629a5-87f5-43c6-ad2e-83bf85e62a76)

2024-03-21 08:38 UTC, arhihihipov commented
Используется контейнер с Whisper, поскольку так изначально посоветовал Марк Маркович. На данный момент не могу сказать, какой из подходов будет более предпочтительным в тренажере

2024-03-21 09:35 UTC, HadronCollider commented
> Используется контейнер с Whisper, поскольку так изначально посоветовал Марк Маркович. На данный момент не могу сказать, какой из подходов будет более предпочтительным в тренажере

Да, пока этот вопрос снимаю - обсуждаю с ММ

2024-04-04 12:16 UTC, HadronCollider approved these changes

2024-04-04 12:16 UTC, merged