391 compare student speech to slides text
OSLL/web_speech_trainer pull request #400
Opened 2024-03-14 17:51 UTC by arhihihipov

2024-04-10 07:14 UTC, zmm commented on app/criteria/comparison_speech_slides/criterion.py
> +russian_stop_words = stopwords.words('russian')
Оберните эти три строки в функцию и вызывайте там, где нужны russian_stop_words

2024-04-10 13:03 UTC, arhihihipov commented on app/criteria/comparison_speech_slides/criterion.py
> +russian_stop_words = stopwords.words('russian')
Это действительно необходимо? Если обернуть это в функцию, то скачивание punkt и stopwords будет происходить каждый раз, когда будет вызываться функция normalize_text
В общем случае это будет 2 * n вызовов, где n -- число слайдов презентации

2024-04-21 19:41 UTC, HadronCollider requested changes

2024-04-21 19:41 UTC, HadronCollider commented on app/db_versioning/versions.py
> +            10: 'ComparisonPack'
тут не трогайте -- это столетнее старье, когда мы перевели наборы с числовых на строковые ID

2024-04-21 19:41 UTC, HadronCollider commented on requirements.txt
> +gensim
Установите версии

2024-04-21 19:41 UTC, HadronCollider commented on app/criteria/comparison_speech_slides/criterion.py
> +            # n-grams
очень хочется вынести отдельные методы сравнения в отдельные соответствующие функции/методы

2024-04-21 19:41 UTC, HadronCollider commented on app/utils.py
> +class RussianStopwords(metaclass=Singleton):
Поправил работу с nltk.download - вынес с стартовый модуль и сделал volume между контейнерами, использующими nltk (чтобы каждый из них не загружал нужные словари каждый в себя)

2024-07-22 14:41 UTC, closed without merging