Whisper split audio before trancribe
OSLL/web_speech_trainer pull request #404
Opened 2024-04-09 16:41 UTC by arhihihipov

2024-04-10 13:20 UTC, HadronCollider requested changes

2024-04-10 13:20 UTC, HadronCollider commented on app/audio_recognizer.py
> +            start_time = end_time
- Вынесите сегментирование в отдельную функцию
- добавьте два параметра (и соответственно две возможности разбиения)
  - delta (по умолчанию 30) - длина сегментов, на которые надо разбить аудио
  - n (по умолчанию None) - количество частей, на которое нужно разбить аудио
  -  если задан параметр n - игнорировать delta, иначе использовать delta

2024-04-10 13:20 UTC, HadronCollider commented on app/audio_recognizer.py
>          for segment in data["segments"]:
Кажется, таким образом мы получим только последние data из цикла?

2024-04-10 13:20 UTC, HadronCollider commented on app/audio_recognizer.py
> +        # Распознавание речи по сегментам
А из-за при подобном подходе не происходит переотправки аудио на распознание (как не было с vosk, но как было с whisper изначально)?

2024-04-10 13:20 UTC, HadronCollider commented on app/audio_processor.py
> +    def __init__(self, resend_stuck_audio_timeout_seconds=30, is_stuck_predicate=default_is_stuck_predicate):
Кажется, осталось после дебага?
Зачем переотправлять аудио чаще (30 секунд вместо 3х минут)

2024-04-10 13:26 UTC, arhihihipov commented on app/audio_processor.py
> +    def __init__(self, resend_stuck_audio_timeout_seconds=30, is_stuck_predicate=default_is_stuck_predicate):
Это я еще на этапе внедрения Whisper протащил в пулл-реквест
https://github.com/OSLL/web_speech_trainer/pull/388/files#diff-bb7ac7512374a23a9e6edefee55e9aa1fa8b4fdcd14ce54af70811902834901fL88

Мне кажется, что этот параметр отвечает не за частоту переотправки, а за частоту "сканирования статуса". Переотправка происходит вот здесь https://github.com/OSLL/web_speech_trainer/blob/master/app/audio_processor.py#L83
Это фиксированное время, равное удвоенной длине аудиозаписи

2024-04-10 13:29 UTC, arhihihipov commented on app/audio_recognizer.py
> +        # Распознавание речи по сегментам
Происходит. Я в письме Gmail писал об этом

2024-04-10 13:32 UTC, arhihihipov commented on app/audio_recognizer.py
> +        # Распознавание речи по сегментам
Здесь я бы хотел узнать, как происходит ресенд аудио, которое система проклассифицировала как застрявшее. Если она ожидает, что аудио будет обработано за время 2*t, где t -- длительность аудио (https://github.com/OSLL/web_speech_trainer/blob/master/app/audio_processor.py#L83), то нужно посмотреть на мощность сервера и подогнать таймаут так, чтобы аудио успевало обработаться целиком. Думаю, с Vosk не происходило переотправки потому, что Vosk работал быстрее, чем Whisper

2024-04-11 11:13 UTC, arhihihipov commented on app/audio_recognizer.py
>          for segment in data["segments"]:
Согласен. Исправил

2024-04-21 20:38 UTC, HadronCollider approved these changes

2024-04-21 20:39 UTC, merged