[WIP] [WST-6] Создать страничку с выгрузкой и просмотров pdf с тайм-кодами слайдов
OSLL/web_speech_trainer pull request #7
Opened 2020-09-09 00:08 UTC by Plyushchenko

2020-09-09 08:16 UTC, zmm requested changes

2020-09-09 08:16 UTC, zmm commented on app/web_speech_trainer.py
> +if __name__ == '__main__':
Нужно настроить дефолтную страницу - ту, которая откроется при переходе на /

2020-09-09 08:16 UTC, zmm commented on app/templates/training.html
> +            alert("Thanks!");
алерты в будущем лучше заменить на https://itchief.ru/bootstrap/alerts
Если нужен отладочный вывод, то console.log('')

2020-09-09 08:16 UTC, zmm commented on app/templates/training.html
> +            document.getElementById("pdf").setAttribute('data', '{{ name }}#zoom=Fit&page='+ currentPage);
Раз у нас подключена jquery, то к элементам удобнее обращатся через $() - для данного случая это будет

```
$('#pdf')
```

2020-09-09 08:16 UTC, zmm commented on app/templates/training.html
> +    <button type="button" id="done" onclick="submitDone()">done</button>
Обработчики кнопок лучше задавать в JS - https://api.jquery.com/click/
Как организовать точку входа на JS (событие ondocumentready) https://learn.jquery.com/using-jquery-core/document-ready/

2020-09-09 08:16 UTC, zmm commented on app/web_speech_trainer.py
> +        presentations.save(request.files['presentation'], name=name)
Лучше сохранить оригинальное название

2020-09-09 08:16 UTC, zmm commented on app/web_speech_trainer.py
> +    if 'presentation' in request.files:
Я бы еще проверил метод страницы - если POST и задан аргумент

2020-09-09 08:18 UTC, Plyushchenko commented on app/web_speech_trainer.py
> +        presentations.save(request.files['presentation'], name=name)
А если несколько пользователей загрузят файлик slides.pdf, то как их отличать в бд?

2020-09-16 01:28 UTC, Plyushchenko commented on app/static/js/training.js
> +var url = 'static/test.pdf';
Я пока что не понял, как из бд передать файл в js

2020-09-23 08:25 UTC, zmm approved these changes

2020-09-23 08:26 UTC, merged